Split out barclamp forkiing logic.

diff --git a/dev b/dev
--- a/dev
+++ b/dev
@@ -323,6 +323,26 @@ crowbar_is_clean() {
 
 test_remote() { git ls-remote "$1" "refs/heads/master" &> /dev/null; }
 
+fork_barclamp() {
+    # $1 = remote to fork from.  Must be a github remote.
+    # $2 = barclamp to fork.
+    # $3 = remote on Github to fork to.  Must be on Github. and defaults to personal.
+    local from_remote="$(remote_urlbase $"1")"
+    local to_remote="$(remote_urlbase "${3:-personal}")"
+    if ! [[ $from_remote && $from_remote =~ $github_re ]]; then
+        die "Source remote $1 is not Github remote!"
+    elif ! [[ $to_remote && $to_remote =~ $github_re ]]; then
+        [[ $3 ]] && die "Target remote $3 is not a Github remote!"
+        [[ $to_remote ]] || die "Personal remote not configured, cannot fork $2 to it."
+        die "Personal remote does not point at a Github remote, cannot fork $2 to it."
+    elif [[ $to_remote != */$DEV_GITHUB_ID ]]; then
+        die "Remote ${3:-personal} does not map to your Github account!"
+    fi
+    test_remote "$to_remote/barclamp-$2.git" && return 0 # already forked
+    test_remote "$from_remote/barclamp-$2.git" || die "Barclamp $2 does not exist at remote $1"
+    github_fork "$1" "barclamp-$2"
+}
+
 # Perform an initial clone of a barclamp.  Takes care to ensure that
 # the origin remote is set appropriatly.
 clone_barclamp() {
@@ -336,7 +356,7 @@ clone_barclamp() {
 	test_remote "$urlbase/$repo.git" || continue
 	if [[ $urlbase =~ $github_re ]] && remote_available personal; then
 	    # test to see if we need to fork this barclamp at Github
-	    github_repo_exists "$repo" || github_fork "$remote" "$repo" || \
+	    github_repo_exists "$repo" || fork_barclamp "$remote" "$1" || \
 		die "Unable to fork $repo on Github. clone_barclamp giving up."
 	fi
 	in_repo git clone "$urlbase/$repo.git" "barclamps/$1" || {
