Add gitify-meta command.

diff --git a/dev b/dev
--- a/dev
+++ b/dev
@@ -3715,6 +3715,41 @@ flatten_crowbar() {
     switch_release
 }
 
+# Transition from flat metadata to git tracked metadata.
+git_track_crowbar_metadata() {
+    local tmp_metadata="$CROWBAR_DIR/.releases"
+    flat_checkout || die "Crowbar metadata is not flat, cannot convert to git tracked!"
+    rm -rf "$tmp_metadata"
+    mkdir -p "$tmp_metadata"
+    (   cd "$tmp_metadata"
+        git init .
+        git checkout master
+        cat >README.crowbar-metadata <<EOF
+This is the crowbar release metadata tracking repository.
+There is a branch in this repository for each release of Crowbar
+that contains all the metadata for that release and the builds that
+are part of that release.
+EOF
+        git add README.crowbar-metadata
+        git commit -m "Initial commit")
+    local working_release
+    while read working_release; do
+        echo "Adding $working_release to git release tracking repository"
+        cfg_dir="$(release_cfg_dir "$working_release")"
+        (cd "$tmp_metadata"; git checkout master; git checkout -b "$working_release")
+        cp -a "$cfg_dir/"* "$tmp_metadata"
+        (cd "$tmp_metadata"; git add .; git commit -m "Added initial metadata for $working_release")
+    done < <(all_releases)
+    echo "Conversion to git tracked metadata finished."
+    echo "To use git tracked metadata, perform the following steps:"
+    echo
+    echo "\$ git rm -rf releases"
+    echo "\$ git commit -m \"Removing flat metadata in favor of git-tracked release metadata\""
+    echo "\$ mv .releases releases"
+    echo
+    echo "After doing this, your releases will be tracked using the git repo based metadata."
+}
+
 # Purge submodule information from the master branch.
 # Should only be used after you have flattend Crowbar and
 # are happy with the results.
@@ -4273,6 +4308,7 @@ DEV_COMMANDS["fetch"]="fetch_all"
 DEV_COMMANDS["fetch-pull-requests"]="fetch_pull_requests_for_remote"
 DEV_COMMANDS["find-parent"]="find_best_parent"
 DEV_COMMANDS["flatten"]="flatten_crowbar"
+DEV_COMMANDS["gitify-meta"]="git_track_crowbar_metadata"
 DEV_COMMANDS["help"]="dev_help"
 DEV_COMMANDS["is_clean"]="crowbar_is_clean"
 DEV_COMMANDS["local-changes"]="find_local_changed_branches_for_release"
@@ -4331,6 +4367,7 @@ DEV_SHORT_HELP["fetch"]="              Fetch updates from configured upstream re
 DEV_SHORT_HELP["fetch-pull-requests"]="Fetch pull request information from a specific remote"
 DEV_SHORT_HELP["find-parent"]="        Find the closest parent of a release or feature."
 DEV_SHORT_HELP["flatten"]="            Flatten the main Crowbar repo branching structure."
+DEV_SHORT_HELP["gitify-meta"]="        Take flattened Crowbar metadata and put it in its own Git repo."
 DEV_SHORT_HELP["help"]="               Show detailed help."
 DEV_SHORT_HELP["is_clean"]="           Test to see if all work is committed."
 DEV_SHORT_HELP["local-changes"]="      Find local changes from upstream for a release"
@@ -4767,6 +4804,8 @@ DEV_LONG_HELP["ci"]="Crowbar Continuous Integration Helper.
     show-intents: Shows all the current and stale intents for a pull request.
     kill-stale-intents: Given a pull request ID, this will kill any stale intents
       that are hanging around and attempt to push them out."
+DEV_LONG_HELP["gitify-meta"]="Translate flattened Crowbar metadata from the releases/
+directory hierarchy, and put it in its own Git repository."
 
 # Verify that we have help for all commands, and exit if we don't.
 for cmd in "${!DEV_COMMANDS[@]}"; do
