Make sure that we always create forks for personal on Github if we can.

diff --git a/dev b/dev
--- a/dev
+++ b/dev
@@ -328,7 +328,7 @@ fork_barclamp() {
     # $1 = remote to fork from.  Must be a github remote.
     # $2 = barclamp to fork.
     # $3 = remote on Github to fork to.  Must be on Github. and defaults to personal.
-    local from_remote="$(remote_urlbase $"1")"
+    local from_remote="$(remote_urlbase "$1")"
     local to_remote="$(remote_urlbase "${3:-personal}")"
     if ! [[ $from_remote && $from_remote =~ $github_re ]]; then
         die "Source remote $1 is not Github remote!"
@@ -400,23 +400,28 @@ find_origin_remote_for_barclamp() {
 clone_and_sync_barclamp() {
     # $1 = name of the barclamp
     local repo remote build head urlbase
+    remote=$(find_origin_remote_for_barclamp "$1") || \
+        die "Cannot find a remote that has barclamp-$1!"
+    urlbase="$(remote_urlbase "$remote")"
     if ! [[ -d $CROWBAR_DIR/barclamps/$1/.git || \
 	-f $CROWBAR_DIR/barclamps/$1/.git ]]; then
         repo="barclamp-$1"
-        remote=$(find_origin_remote_for_barclamp "$1") || \
-            die "Cannot find a remote that has $repo!"
-        urlbase="$(remote_urlbase "$remote")"
-        if [[ $urlbase =~ $github_re ]] && remote_available personal; then
-	    # test to see if we need to fork this barclamp at Github
-	    github_repo_exists "$repo" || fork_barclamp "$remote" "$1" || \
-	        die "Unable to fork $repo on Github. clone_barclamp giving up."
-        fi
         in_repo git clone "$urlbase/$repo.git" "barclamps/$1" || {
 	    rm -rf "$CROWBAR_DIR/barclamps/$1"
 	    die "Unable to clone barclamp $bc from $urlbase/$repo.git"
         }
     fi
     sync_barclamp_remotes "$1"
+    if [[ $urlbase =~ $github_re ]] && remote_available personal && \
+        ! in_barclamp "$1" git_remote_exists personal; then
+	    # test to see if we need to fork this barclamp at Github
+	if ! github_repo_exists "barclamp-$1"; then
+            debug "Creating a personal fork of barclamp-$1"
+            fork_barclamp "$remote" "$1" || \
+	        die "Unable to fork $repo on Github. clone_barclamp giving up."
+                sync_barclamp_remotes "$1"
+        fi
+    fi
     in_barclamp "$1" git_remote_exists origin && in_barclamp "$1" git remote rm origin
     in_barclamp "$1" update_tracking_branches
 }
@@ -424,9 +429,15 @@ clone_and_sync_barclamp() {
 clone_barclamps() {
     # $@ = barclamps to clone.  If none are passed, defaults to missing ones.
     local barclamps=() bc
-    [[ $@ ]] && barclamps=("$@") || barclamps=($(find_missing_barclamps))
+    if [[ $1 = all ]]; then
+        barclamps=($(all_barclamps))
+    elif [[ $1 ]]; then
+        barclamps=("$@")
+    else
+        barclamps=($(find_missing_barclamps))
+    fi
     for bc in "${barclamps[@]}"; do
-        clone_barclamp "$bc"
+        clone_and_sync_barclamp "$bc"
     done
 }
 
@@ -589,7 +600,8 @@ scrub_merged_pulls() {
 
 # Helper function for calling curl to talk to github.
 curl_and_res() {
-    local __r="$(curl -n "$@" 2>/dev/null)"
+    local __r
+    __r="$(curl -n "$@" 2>/dev/null)"
     case $? in
 	0) printf '%s' "$__r";;
 	7) echo "Unable to contact Github, please try again later." >&2
@@ -604,7 +616,7 @@ github_repo_exists() {
     # $1 = repo to check for
     # $2 = user to check for it in.  Defaults to $DEV_GITHUB_ID
     local repo=$1 user=${2-$DEV_GITHUB_ID}
-    curl_and_res -f -X GET "https://api.github.com/repos/$user/$repo" >&/dev/null
+    curl_and_res -f -X GET "https://api.github.com/repos/$user/$repo" &>/dev/null
 }
 
 # Fork a repository on Github.
@@ -670,8 +682,8 @@ sync_barclamp_remotes() {
     # We will ignore the origin remote.
     local remote urlbase remote_repo barclamp_repo
     while read remote urlbase; do
-	remote_repo=$(in_barclamp "$1" git_url_for_remote "$remote") || continue
-	[[ ${remote_repo%.git} = $urlbase/barclamp-$1 ]] && continue
+	remote_repo=$(in_barclamp "$1" git_url_for_remote "$remote") && \
+	    [[ ${remote_repo%.git} = $urlbase/barclamp-$1 ]] && continue
 	debug "Synchronizing remote $remote for barclamp $1"
 	if in_barclamp "$1" git_remote_exists "$remote"; then
 	    in_barclamp "$1" set_url_remote "$remote" "$urlbase" || continue
